apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: influxdb-pvc
        labels:
                app: influxdb
                project: twittergraph
spec:
        accessModes:
        - ReadWriteOnce
        resources:
                requests:
                        storage: 2Gi


